triggers:
  - name: tgrtest1
    type: trigger
    source:
      message: 'testing trigger jobs in yml'

  - name: trgtest2
    type: trigger
    source:
      counter: 1
       
  - name: tgrtest3
    type: trigger
    source:
      counter: 1
