triggers:
  - name: triggerbg1
    type: trigger
    pointer:
      message: 'test triggering jobssss in jobs.yml'
      
  - name: triggerbg2
    type: trigger
    pointer:
      counter: 20
      
  - name: triggerbg3
    type: trigger
    pointer:
      counter: 4
      
  - name: triggerbg4
    type: trigger
    pointer:
      counter: 2
      
  - name: triggerbg5
    type: trigger
    pointer:
      counter: 2
      
  - name: triggerup1
    type: trigger
    pointer:
      message: 'test triggering job in jobs.yml'
      
  - name: triggerup2
    type: trigger
    pointer:
      counter: 1
      
  - name: triggerup3
    type: trigger
    pointer:
      counter: 1
