triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'testing trigger in yml'

  - name: triggertptest2
    type: trigger
    source:
      counter: 1
       
  - name: triggertptest3
    type: trigger
    source:
      counter: 1
       
  - name: triggertesttp4
    type: trigger
    source:
      counter: 2
      
  - name: triggertesttp5
    type: trigger
    source:
      counter: 2
