triggers:
  - name: triggerbg1
    type: trigger
    pointer:
      message: 'test triggering jobssss in jobs.yml'
      
  - name: triggerbg2
    type: trigger
    pointer:
      counter: 4
      
  - name: triggerbg3
    type: trigger
    pointer:
      counter: 1
