jobs:
  - name: tri-bgmanifest1
    type: manifest
    steps:
      - GET: tri-img1
      - GET: triggerbg1
    #  - GET: tri-param2
    #  - GET: tri-dopt1
    
  - name: tri-bgmanifest2
    type: manifest
    steps:
      - GET: tri-img1
      #- GET: triggerbg2
      #- GET: tri-param2
      #- GET: tri-dopt1
      - GET: tri-replica1
      
  - name: tri-bgmanifest3
    type: manifest
    steps:
      - GET: tri-img2
      - GET: triggerbg2
      - GET: tri-param3
      - GET: tri-dopt3
      
  - name: tri-bgmanifest4
    type: manifest
    steps:
      - GET: tri-img1
      - GET: triggerbg3
      - GET: tri-dopt1
      
  - name: tri-bgmanifest5
    type: manifest
    steps:
      - GET: tri-img2
      - GET: triggerbg3
      - GET: tri-dopt2
      
  - name: tri-bgmanifest6
    type: manifest
    steps:
      - GET: tri-img2
      - GET: tri-img1
      - GET: triggerbg4
    
  - name: tri-bgmanifest7
    type: manifest
    steps:
      - GET: tri-img6
      - GET: triggerbg5
      
  - name: tp-tritondeploybg1
    type: tripubDeploy
    options: 
      deployMethod: blueGreen
    steps:
      - GET: tri-bgmanifest1
      - GET: tp-tpcluster2
      
  - name: tp-tritondeploybg4
    type: tripubDeploy
    options: 
      deployMethod: blueGreen
    steps:
      - GET: tri-bgmanifest2
      - GET: tri-bgmanifest3
      - GET: tp-tpcluster2
     # - GET: tp-replica2
     # - GET: tri-dopt2

  - name: tp-tritondeploybg6
    type: tripubDeploy
    options: 
      deployMethod: blueGreen
    steps:
      - GET: tri-bgmanifest2
      - GET: tri-bgmanifest3
      - GET: tp-tpcluster2
     # - GET: tp-replica2
     # - GET: tri-dopt2
     
  - name: tp-tritondeploybg7
    type: tripubDeploy
    options: 
      deployMethod: blueGreen
    steps:
      - GET: tri-bgmanifest4
      - GET: tri-bgmanifest5
      - GET: tp-tpcluster2
      
  - name: tp-tritondeploybg8
    type: tripubDeploy
    options: 
      deployMethod: blueGreen
    steps:
      - GET: tri-bgmanifest6
      - GET: tp-tpcluster2
      
  - name: tp-tritondeploybg9
    type: tripubDeploy
    options: 
      deployMethod: blueGreen
    steps:
      - GET: tri-bgmanifest7
      - GET: tp-tpcluster2
     
  - name: tri-upmanifest1
    type: manifest
    steps:
      - GET: tri-img1
      - GET: triggerup1
      
  - name: tp-uptritondeploy1
    type: tripubDeploy
    options: 
      deployMethod: upgrade
    steps:
      - GET: tri-upmanifest1
      - GET: tp-tpcluster2
