triggers:
  - name: triggerbgt1
    type: trigger
    source:
      message: 'testing trigger in jobs.yml'
      
  - name: triggerbgt2
    type: trigger
    source:
      counter: 1
      
  - name: triggerbgt3
    type: trigger
    source:
      counter: 1
