triggers:
  - name: triggerbg1
    type: trigger
    source:
      message: 'testing trigger jobs in yml'
      
  - name: triggerbg2
    type: trigger
    source:
      counter: 1
      
  - name: triggerbg3
    type: trigger
    source:
      counter: 1
