jobs:
  - name: tri-manifest1
    type: manifest
    steps:
      - GET: tri-img2
      - GET: tgrtest1
      - GET: tp-param1
      - GET: tp-dopt1
      - GET: tp-replica2
     
  - name: tp-testdeploy1
    type: tripubDeploy
    steps:
      - GET: tritest-tpcluster
      - GET: tri-manifest1
    
  #- name: repo-dcldeploy
   # type: dclDeploy
    #steps:
     # - GET: repo-manifest
      #- GET: repo-dclcluster
      #- GET: repo-replica1
    
  #- name: repo-ecsdeploytodcldeploy
   # type: dclDeploy
    #steps:
     # - GET: repo-ecsdeploy
      #- GET: repo-dclcluster
      
#  - name: multimanifest-dcldeploy
 #   type: dclDeploy
  #  steps:
   #   - GET: repo-manifest
    #  - GET: repo-manifest2
     # - GET: repo-dclcluster
      
