jobs:
  - name: tri-bgtmanifest1
    type: manifest
    steps:
      - GET: tri-bgtimg2
      - GET: triggerbgt1
      - GET: tri-bgtparam3
      - GET: tri-bgtdopt1
      
  - name: tri-bgtdeploy1
    type: tripubDeploy
    options: 
      deployMethod: bluegreen
    steps:
      - GET: tri-bgtmanifest1
      - GET: tp-tpcluster3
     
#  - name: repo-ecsdeploy
 #   type: ecsDeploy
  #  steps:
   #   - GET: repo-manifest2
    #  - GET: repo-ecscluster
    
  #- name: repo-dcldeploy
   # type: dclDeploy
    #steps:
     # - GET: repo-manifest
      #- GET: repo-dclcluster
      #- GET: repo-replica1
    
  #- name: repo-ecsdeploytodcldeploy
   # type: dclDeploy
    #steps:
     # - GET: repo-ecsdeploy
      #- GET: repo-dclcluster
      
#  - name: multimanifest-dcldeploy
 #   type: dclDeploy
  #  steps:
   #   - GET: repo-manifest
    #  - GET: repo-manifest2
     # - GET: repo-dclcluster
      
